onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Logic /gopf_mul_tb/uut/clk
add wave -noupdate -format Logic /gopf_mul_tb/uut/rst_b
add wave -noupdate -format Logic /gopf_mul_tb/uut/start
add wave -noupdate -format Literal /gopf_mul_tb/uut/multiplicand
add wave -noupdate -format Literal /gopf_mul_tb/uut/multiplier
add wave -noupdate -format Literal /gopf_mul_tb/uut/mod
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/NextState
add wave -noupdate -color Gold -format Literal -radix unsigned /gopf_mul_tb/uut/CurrentState
add wave -noupdate -format Logic /gopf_mul_tb/uut/finish
add wave -noupdate -format Logic /gopf_mul_tb/uut/overflow
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul_cnt
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul_o_reg
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul_t_reg
add wave -noupdate -format Literal /gopf_mul_tb/uut/mod_reg
add wave -noupdate -color Blue -format Literal /gopf_mul_tb/uut/mul_r_reg
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul_o_in_reg
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul_t_in_reg
add wave -noupdate -color Magenta -format Literal -radix unsigned /gopf_mul_tb/uut/counter
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul1_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul2_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul3_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul4_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul5_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul6_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul7_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul8_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul9_o_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul_t_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul1_r_dat
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul2_r_dat
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul3_r_dat
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul4_r_dat
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul5_r_dat
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul6_r_dat
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul7_r_dat
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul8_r_dat
add wave -noupdate -format Literal /gopf_mul_tb/uut/mul9_r_dat
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL01/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL01/my_Mul_ModularX82/Q_out
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL02/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL02/my_Mul_ModularX82/Q_out
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL03/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL03/my_Mul_ModularX82/Q_out
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL04/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL04/my_Mul_ModularX82/Q_out
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL05/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL05/my_Mul_ModularX82/Q_out
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL06/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL06/my_Mul_ModularX82/Q_out
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL07/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL07/my_Mul_ModularX82/Q_out
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL08/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL08/my_Mul_ModularX82/Q_out
add wave -noupdate -format Logic /gopf_mul_tb/uut/BF_MUL09/clk
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/A_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/B_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/C_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/A_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/B_inv_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/C_inv_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/i
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/AHBHMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/ALBLMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/ZAZBMulNet
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/Sub
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/AHBHMulX8
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/AHBHMulX16
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/Z1Net
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/AHALAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/BHBLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/AHBHMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/ALBLMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/ZAZBMul
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/PHPLAdd
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/ALBLMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/AHBHMul1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/Z1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/Z0Z2Add
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore0/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore1/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/a_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/b_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/c_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product0_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product0_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product0_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product0_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product0_4
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product0_5
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product0_6
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product0_7
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product1_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product1_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product1_2
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product1_3
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product2_0
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_MultiCore2/partial_product2_1
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_ModularX80/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_ModularX80/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_ModularX81/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_ModularX81/Q_out
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_ModularX82/D_in
add wave -noupdate -format Literal /gopf_mul_tb/uut/BF_MUL09/my_Mul_ModularX82/Q_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {136 ns} 0} {{Cursor 2} {215 ns} 0} {{Cursor 3} {255 ns} 0} {{Cursor 4} {999 ns} 0} {{Cursor 5} {2085 ns} 0} {{Cursor 6} {3265 ns} 0}
configure wave -namecolwidth 312
configure wave -valuecolwidth 179
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {2304 ns} {2405 ns}
